services:
  ingest:
    build:
      dockerfile: Dockerfile.ingest
    ports:
      - "8502:8502"
    volumes:
      - $PWD/auth:/home/intheirownwords/auth
      - $PWD/prj:/home/intheirownwords/prj
      - $PWD/env:/home/intheirownwords/env
      - $PWD/ingest:/home/intheirownwords/ingest
      - /usr/local/cuda:/usr/local/cuda
      - $PWD/cache:/root/.cache
    env_file:
      - env/env.vars
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: on-failure
  ui:
    build:
      dockerfile: Dockerfile.ui
    ports:
      - "80:8501"
    volumes:
      - $PWD/auth:/home/intheirownwords/auth
      - $PWD/prj:/home/intheirownwords/prj
      - $PWD/env:/home/intheirownwords/env
      - $PWD/ingest:/home/intheirownwords/ingest
    env_file:
      - env/env.vars
    restart: on-failure